// DO NOT EDIT: File is generated by code generator.
package jp.pokepay.pokepay_sdk;

import io.flutter.plugin.common.MethodCall;

import jp.pokepay.pokepaylib.Env;
import jp.pokepay.pokepaylib.Pokepay;
import jp.pokepay.pokepaylib.BankAPI.autogen.requests.*;
import jp.pokepay.pokepaylib.BankAPI.autogen.responses.*;
import jp.pokepay.pokepaylib.Responses.NoContent;
import jp.pokepay.pokepaylib.Responses.IdentificationResult;

class AutogenMethodHandlers {
    private static Env flutterEnvToSDKEnv(int env) {
        switch (env) {
            case 0: return Env.PRODUCTION;
            case 1: return Env.SANDBOX;
            case 2: return Env.QA;
            case 3: return Env.DEVELOPMENT;
            case 4: return Env.TOPIC1;
            case 5: return Env.TOPIC2;
            case 6: return Env.TOPIC3;
            case 7: return Env.LOADTEST;
            default: return Env.DEVELOPMENT;
        }
    }

    // 自動生成 API のメソッド呼び出しを処理する。対応しないメソッド名なら null を返す。
    static String handle(MethodCall call) throws Exception {
        switch (call.method) {
            case "getTransactionByRequestId": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String requestId = call.argument("request_id");
                if (requestId == null) requestId = call.argument("requestId");
                GetTransactionByRequestId req = new GetTransactionByRequestId(requestId);
                Pokepay.setEnv(env);
                UserTransactionWithTransfers res = req.send(accessToken);
                return res.toString();
            }
            case "createCashtrayTransaction": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String requestId = call.argument("request_id");
                if (requestId == null) requestId = call.argument("requestId");
                String cashtrayId = call.argument("cashtray_id");
                if (cashtrayId == null) cashtrayId = call.argument("cashtrayId");
                String accountId = call.argument("account_id");
                if (accountId == null) accountId = call.argument("accountId");
                String couponId = call.argument("coupon_id");
                if (couponId == null) couponId = call.argument("couponId");
                String strategy = call.argument("strategy");
                Integer topupQuotaId = call.argument("topup_quota_id");
                if (topupQuotaId == null) topupQuotaId = call.argument("topupQuotaId");
                CreateCashtrayTransaction req = new CreateCashtrayTransaction(requestId, cashtrayId);
                req = req.accountId(accountId);
                req = req.couponId(couponId);
                req = req.strategy(strategy);
                req = req.topupQuotaId(topupQuotaId);
                Pokepay.setEnv(env);
                UserTransactionWithFallback res = req.send(accessToken);
                return res.toString();
            }
            case "createBillTransaction": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String requestId = call.argument("request_id");
                if (requestId == null) requestId = call.argument("requestId");
                String billId = call.argument("bill_id");
                if (billId == null) billId = call.argument("billId");
                String accountId = call.argument("account_id");
                if (accountId == null) accountId = call.argument("accountId");
                Double amount = call.argument("amount");
                String couponId = call.argument("coupon_id");
                if (couponId == null) couponId = call.argument("couponId");
                String strategy = call.argument("strategy");
                CreateBillTransaction req = new CreateBillTransaction(requestId, billId);
                req = req.accountId(accountId);
                req = req.amount(amount);
                req = req.couponId(couponId);
                req = req.strategy(strategy);
                Pokepay.setEnv(env);
                UserTransactionWithFallback res = req.send(accessToken);
                return res.toString();
            }
            case "createCheckTransaction": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String checkId = call.argument("check_id");
                if (checkId == null) checkId = call.argument("checkId");
                String requestId = call.argument("request_id");
                if (requestId == null) requestId = call.argument("requestId");
                String accountId = call.argument("account_id");
                if (accountId == null) accountId = call.argument("accountId");
                Integer topupQuotaId = call.argument("topup_quota_id");
                if (topupQuotaId == null) topupQuotaId = call.argument("topupQuotaId");
                CreateCheckTransaction req = new CreateCheckTransaction(checkId);
                req = req.requestId(requestId);
                req = req.accountId(accountId);
                req = req.topupQuotaId(topupQuotaId);
                Pokepay.setEnv(env);
                UserTransactionWithFallback res = req.send(accessToken);
                return res.toString();
            }
            case "getCreditCards": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String userId = call.argument("user_id");
                if (userId == null) userId = call.argument("userId");
                String organizationCode = call.argument("organization_code");
                if (organizationCode == null) organizationCode = call.argument("organizationCode");
                String before = call.argument("before");
                String after = call.argument("after");
                Integer perPage = call.argument("per_page");
                if (perPage == null) perPage = call.argument("perPage");
                GetCreditCards req = new GetCreditCards(userId, organizationCode);
                req = req.before(before);
                req = req.after(after);
                req = req.perPage(perPage);
                Pokepay.setEnv(env);
                PaginatedCreditCards res = req.send(accessToken);
                return res.toString();
            }
            case "createCreditCard": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String userId = call.argument("user_id");
                if (userId == null) userId = call.argument("userId");
                String token = call.argument("token");
                String organizationCode = call.argument("organization_code");
                if (organizationCode == null) organizationCode = call.argument("organizationCode");
                Boolean isCardholderNameSpecified = call.argument("is_cardholder_name_specified");
                if (isCardholderNameSpecified == null) isCardholderNameSpecified = call.argument("isCardholderNameSpecified");
                CreateCreditCard req = new CreateCreditCard(userId, token, organizationCode);
                req = req.isCardholderNameSpecified(isCardholderNameSpecified);
                Pokepay.setEnv(env);
                CreditCard res = req.send(accessToken);
                return res.toString();
            }
            case "deleteCreditCard": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String userId = call.argument("user_id");
                if (userId == null) userId = call.argument("userId");
                String organizationCode = call.argument("organization_code");
                if (organizationCode == null) organizationCode = call.argument("organizationCode");
                String cardRegisteredAt = call.argument("card_registered_at");
                if (cardRegisteredAt == null) cardRegisteredAt = call.argument("cardRegisteredAt");
                String cardUuid = call.argument("card_uuid");
                if (cardUuid == null) cardUuid = call.argument("cardUuid");
                DeleteCreditCard req = new DeleteCreditCard(userId, organizationCode);
                req = req.cardRegisteredAt(cardRegisteredAt);
                req = req.cardUuid(cardUuid);
                Pokepay.setEnv(env);
                NoContent res = req.send(accessToken);
                return res.toString();
            }
            case "topupWithCreditCardMembership": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String userId = call.argument("user_id");
                if (userId == null) userId = call.argument("userId");
                String accountId = call.argument("account_id");
                if (accountId == null) accountId = call.argument("accountId");
                Integer amount = call.argument("amount");
                String organizationCode = call.argument("organization_code");
                if (organizationCode == null) organizationCode = call.argument("organizationCode");
                String cardRegisteredAt = call.argument("card_registered_at");
                if (cardRegisteredAt == null) cardRegisteredAt = call.argument("cardRegisteredAt");
                String cardUuid = call.argument("card_uuid");
                if (cardUuid == null) cardUuid = call.argument("cardUuid");
                Boolean deleteCardIfAuthFail = call.argument("delete_card_if_auth_fail");
                if (deleteCardIfAuthFail == null) deleteCardIfAuthFail = call.argument("deleteCardIfAuthFail");
                String requestId = call.argument("request_id");
                if (requestId == null) requestId = call.argument("requestId");
                Integer topupQuotaId = call.argument("topup_quota_id");
                if (topupQuotaId == null) topupQuotaId = call.argument("topupQuotaId");
                TopupWithCreditCardMembership req = new TopupWithCreditCardMembership(userId, accountId, amount, organizationCode);
                req = req.cardRegisteredAt(cardRegisteredAt);
                req = req.cardUuid(cardUuid);
                req = req.deleteCardIfAuthFail(deleteCardIfAuthFail);
                req = req.requestId(requestId);
                req = req.topupQuotaId(topupQuotaId);
                Pokepay.setEnv(env);
                String res = req.send(accessToken);
                return res;
            }
            case "topupWithCreditCardMdkToken": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String userId = call.argument("user_id");
                if (userId == null) userId = call.argument("userId");
                String token = call.argument("token");
                String accountId = call.argument("account_id");
                if (accountId == null) accountId = call.argument("accountId");
                Integer amount = call.argument("amount");
                String organizationCode = call.argument("organization_code");
                if (organizationCode == null) organizationCode = call.argument("organizationCode");
                Boolean isCardholderNameSpecified = call.argument("is_cardholder_name_specified");
                if (isCardholderNameSpecified == null) isCardholderNameSpecified = call.argument("isCardholderNameSpecified");
                String requestId = call.argument("request_id");
                if (requestId == null) requestId = call.argument("requestId");
                Integer topupQuotaId = call.argument("topup_quota_id");
                if (topupQuotaId == null) topupQuotaId = call.argument("topupQuotaId");
                TopupWithCreditCardMdkToken req = new TopupWithCreditCardMdkToken(userId, token, accountId, amount, organizationCode);
                req = req.isCardholderNameSpecified(isCardholderNameSpecified);
                req = req.requestId(requestId);
                req = req.topupQuotaId(topupQuotaId);
                Pokepay.setEnv(env);
                String res = req.send(accessToken);
                return res;
            }
            case "getCvsAuthorizations": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String accountId = call.argument("account_id");
                if (accountId == null) accountId = call.argument("accountId");
                String before = call.argument("before");
                String after = call.argument("after");
                Integer perPage = call.argument("per_page");
                if (perPage == null) perPage = call.argument("perPage");
                GetCvsAuthorizations req = new GetCvsAuthorizations(accountId);
                req = req.before(before);
                req = req.after(after);
                req = req.perPage(perPage);
                Pokepay.setEnv(env);
                PaginatedCvsAuthorizations res = req.send(accessToken);
                return res.toString();
            }
            case "cvsAuthorizeRequest": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String accountId = call.argument("account_id");
                if (accountId == null) accountId = call.argument("accountId");
                String serviceOptionType = call.argument("service_option_type");
                if (serviceOptionType == null) serviceOptionType = call.argument("serviceOptionType");
                Integer amount = call.argument("amount");
                String name1 = call.argument("name1");
                String name2 = call.argument("name2");
                String tel = call.argument("tel");
                Integer topupQuotaId = call.argument("topup_quota_id");
                if (topupQuotaId == null) topupQuotaId = call.argument("topupQuotaId");
                CvsAuthorizeRequest req = new CvsAuthorizeRequest(accountId, serviceOptionType, amount, name1, name2, tel);
                req = req.topupQuotaId(topupQuotaId);
                Pokepay.setEnv(env);
                CvsAuthorization res = req.send(accessToken);
                return res.toString();
            }
            case "cancelCvsAuthorization": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String accountId = call.argument("account_id");
                if (accountId == null) accountId = call.argument("accountId");
                String orderId = call.argument("order_id");
                if (orderId == null) orderId = call.argument("orderId");
                CancelCvsAuthorization req = new CancelCvsAuthorization(accountId, orderId);
                Pokepay.setEnv(env);
                NoContent res = req.send(accessToken);
                return res.toString();
            }
            case "getCvsAuthorization": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String accountId = call.argument("account_id");
                if (accountId == null) accountId = call.argument("accountId");
                String orderId = call.argument("order_id");
                if (orderId == null) orderId = call.argument("orderId");
                GetCvsAuthorization req = new GetCvsAuthorization(accountId, orderId);
                Pokepay.setEnv(env);
                CvsAuthorization res = req.send(accessToken);
                return res.toString();
            }
            case "getAccountIndividualNumberIdentification": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String accountId = call.argument("account_id");
                if (accountId == null) accountId = call.argument("accountId");
                GetAccountIndividualNumberIdentification req = new GetAccountIndividualNumberIdentification(accountId);
                Pokepay.setEnv(env);
                IndividualNumberIdentificationStatus res = req.send(accessToken);
                return res.toString();
            }
            case "identifyIndividual": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String accountId = call.argument("account_id");
                if (accountId == null) accountId = call.argument("accountId");
                String signature = call.argument("signature");
                String signingCert = call.argument("signing_cert");
                if (signingCert == null) signingCert = call.argument("signingCert");
                String expectedHash = call.argument("expected_hash");
                if (expectedHash == null) expectedHash = call.argument("expectedHash");
                String name = call.argument("name");
                String gender = call.argument("gender");
                String address = call.argument("address");
                String dateOfBirth = call.argument("date_of_birth");
                if (dateOfBirth == null) dateOfBirth = call.argument("dateOfBirth");
                IdentifyIndividual req = new IdentifyIndividual(accountId, signature, signingCert, expectedHash);
                req = req.name(name);
                req = req.gender(gender);
                req = req.address(address);
                req = req.dateOfBirth(dateOfBirth);
                Pokepay.setEnv(env);
                IdentificationResult res = req.send(accessToken);
                return res.toString();
            }
            case "getAccountTopupQuotas": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String accountId = call.argument("account_id");
                if (accountId == null) accountId = call.argument("accountId");
                String status = call.argument("status");
                Boolean showExpiredForFixedPeriod = call.argument("show_expired_for_fixed_period");
                if (showExpiredForFixedPeriod == null) showExpiredForFixedPeriod = call.argument("showExpiredForFixedPeriod");
                Boolean showStartedQuotas = call.argument("show_started_quotas");
                if (showStartedQuotas == null) showStartedQuotas = call.argument("showStartedQuotas");
                Boolean isWithinApplicablePeriod = call.argument("is_within_applicable_period");
                if (isWithinApplicablePeriod == null) isWithinApplicablePeriod = call.argument("isWithinApplicablePeriod");
                Boolean isUsableAmountLeft = call.argument("is_usable_amount_left");
                if (isUsableAmountLeft == null) isUsableAmountLeft = call.argument("isUsableAmountLeft");
                GetAccountTopupQuotas req = new GetAccountTopupQuotas(accountId);
                req = req.status(status);
                req = req.showExpiredForFixedPeriod(showExpiredForFixedPeriod);
                req = req.showStartedQuotas(showStartedQuotas);
                req = req.isWithinApplicablePeriod(isWithinApplicablePeriod);
                req = req.isUsableAmountLeft(isUsableAmountLeft);
                Pokepay.setEnv(env);
                AccountTopupQuotas res = req.send(accessToken);
                return res.toString();
            }
            case "getAccountTopupStats": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String accountId = call.argument("account_id");
                if (accountId == null) accountId = call.argument("accountId");
                GetAccountTopupStats req = new GetAccountTopupStats(accountId);
                Pokepay.setEnv(env);
                AccountTopupStats res = req.send(accessToken);
                return res.toString();
            }
            case "createJihanpiTransaction": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String nfcTagId = call.argument("nfc_tag_id");
                if (nfcTagId == null) nfcTagId = call.argument("nfcTagId");
                String accountId = call.argument("account_id");
                if (accountId == null) accountId = call.argument("accountId");
                String requestId = call.argument("request_id");
                if (requestId == null) requestId = call.argument("requestId");
                String strategy = call.argument("strategy");
                CreateJihanpiTransaction req = new CreateJihanpiTransaction(nfcTagId, accountId);
                req = req.requestId(requestId);
                req = req.strategy(strategy);
                Pokepay.setEnv(env);
                JihanpiTransaction res = req.send(accessToken);
                return res.toString();
            }
            case "getJihanpiTransactionByOrderId": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String orderId = call.argument("order_id");
                if (orderId == null) orderId = call.argument("orderId");
                GetJihanpiTransactionByOrderId req = new GetJihanpiTransactionByOrderId(orderId);
                Pokepay.setEnv(env);
                JihanpiTransaction res = req.send(accessToken);
                return res.toString();
            }
            case "getJihanpiTransactionByRequestId": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String requestId = call.argument("request_id");
                if (requestId == null) requestId = call.argument("requestId");
                GetJihanpiTransactionByRequestId req = new GetJihanpiTransactionByRequestId(requestId);
                Pokepay.setEnv(env);
                JihanpiTransaction res = req.send(accessToken);
                return res.toString();
            }
            case "getDetailedShopInformation": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String shopId = call.argument("shop_id");
                if (shopId == null) shopId = call.argument("shopId");
                GetDetailedShopInformation req = new GetDetailedShopInformation(shopId);
                Pokepay.setEnv(env);
                DetailedShopInformation res = req.send(accessToken);
                return res.toString();
            }
            case "getListOfShops": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String privateMoneyId = call.argument("private_money_id");
                if (privateMoneyId == null) privateMoneyId = call.argument("privateMoneyId");
                String userTagGroupItemId = call.argument("user_tag_group_item_id");
                if (userTagGroupItemId == null) userTagGroupItemId = call.argument("userTagGroupItemId");
                String userTagSubgroupId = call.argument("user_tag_subgroup_id");
                if (userTagSubgroupId == null) userTagSubgroupId = call.argument("userTagSubgroupId");
                String before = call.argument("before");
                String after = call.argument("after");
                Integer perPage = call.argument("per_page");
                if (perPage == null) perPage = call.argument("perPage");
                GetListOfShops req = new GetListOfShops(privateMoneyId);
                req = req.userTagGroupItemId(userTagGroupItemId);
                req = req.userTagSubgroupId(userTagSubgroupId);
                req = req.before(before);
                req = req.after(after);
                req = req.perPage(perPage);
                Pokepay.setEnv(env);
                PaginatedShops res = req.send(accessToken);
                return res.toString();
            }
            case "getUserTagGroups": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String privateMoneyId = call.argument("private_money_id");
                if (privateMoneyId == null) privateMoneyId = call.argument("privateMoneyId");
                String before = call.argument("before");
                String after = call.argument("after");
                Integer perPage = call.argument("per_page");
                if (perPage == null) perPage = call.argument("perPage");
                GetUserTagGroups req = new GetUserTagGroups(privateMoneyId);
                req = req.before(before);
                req = req.after(after);
                req = req.perPage(perPage);
                Pokepay.setEnv(env);
                PaginatedUserTagGroups res = req.send(accessToken);
                return res.toString();
            }
            case "getUserTagGroupItems": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String organizationCode = call.argument("organization_code");
                if (organizationCode == null) organizationCode = call.argument("organizationCode");
                String tagGroupId = call.argument("tag_group_id");
                if (tagGroupId == null) tagGroupId = call.argument("tagGroupId");
                String subgroupId = call.argument("subgroup_id");
                if (subgroupId == null) subgroupId = call.argument("subgroupId");
                String before = call.argument("before");
                String after = call.argument("after");
                Integer perPage = call.argument("per_page");
                if (perPage == null) perPage = call.argument("perPage");
                GetUserTagGroupItems req = new GetUserTagGroupItems(organizationCode, tagGroupId);
                req = req.subgroupId(subgroupId);
                req = req.before(before);
                req = req.after(after);
                req = req.perPage(perPage);
                Pokepay.setEnv(env);
                PaginatedUserTagGroupItems res = req.send(accessToken);
                return res.toString();
            }
            case "getUserTagSubgroups": {
                Env env = flutterEnvToSDKEnv((int) call.argument("env"));
                String accessToken = call.argument("accessToken");
                String organizationCode = call.argument("organization_code");
                if (organizationCode == null) organizationCode = call.argument("organizationCode");
                String tagGroupId = call.argument("tag_group_id");
                if (tagGroupId == null) tagGroupId = call.argument("tagGroupId");
                String before = call.argument("before");
                String after = call.argument("after");
                Integer perPage = call.argument("per_page");
                if (perPage == null) perPage = call.argument("perPage");
                GetUserTagSubgroups req = new GetUserTagSubgroups(organizationCode, tagGroupId);
                req = req.before(before);
                req = req.after(after);
                req = req.perPage(perPage);
                Pokepay.setEnv(env);
                PaginatedUserTagSubgroups res = req.send(accessToken);
                return res.toString();
            }
            default:
                return null;
        }
    }
}
