// DO NOT EDIT: File is generated by code generator.
import Flutter
import Foundation
import Pokepay

extension MethodCallTask {
    // 自動生成 API のメソッド呼び出しを処理する。対応しないメソッド名なら false を返す。
    func handleAutogen(method: String, args: [String : Any]) -> Bool {
        switch method {
        case "getTransactionByRequestId":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let requestId = (args["request_id"] ?? args["requestId"]) as! String
            client.send(BankAPI.Transaction.GetTransactionByRequestId(requestId: requestId), handler: self.after)
        case "createCashtrayTransaction":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let requestId = (args["request_id"] ?? args["requestId"]) as! String
            let cashtrayId = (args["cashtray_id"] ?? args["cashtrayId"]) as! String
            let accountId = (args["account_id"] ?? args["accountId"]) as? String
            let couponId = (args["coupon_id"] ?? args["couponId"]) as? String
            let strategy = args["strategy"] as? String
            let topupQuotaId = (args["topup_quota_id"] ?? args["topupQuotaId"]) as? Int
            client.send(BankAPI.Transaction.CreateCashtrayTransaction(requestId: requestId, cashtrayId: cashtrayId, accountId: accountId, couponId: couponId, strategy: strategy, topupQuotaId: topupQuotaId), handler: self.after)
        case "createBillTransaction":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let requestId = (args["request_id"] ?? args["requestId"]) as! String
            let billId = (args["bill_id"] ?? args["billId"]) as! String
            let accountId = (args["account_id"] ?? args["accountId"]) as? String
            let amount = args["amount"] as? Double
            let couponId = (args["coupon_id"] ?? args["couponId"]) as? String
            let strategy = args["strategy"] as? String
            client.send(BankAPI.Transaction.CreateBillTransaction(requestId: requestId, billId: billId, accountId: accountId, amount: amount, couponId: couponId, strategy: strategy), handler: self.after)
        case "createCheckTransaction":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let requestId = (args["request_id"] ?? args["requestId"]) as? String
            let checkId = (args["check_id"] ?? args["checkId"]) as! String
            let accountId = (args["account_id"] ?? args["accountId"]) as? String
            let topupQuotaId = (args["topup_quota_id"] ?? args["topupQuotaId"]) as? Int
            client.send(BankAPI.Transaction.CreateCheckTransaction(requestId: requestId, checkId: checkId, accountId: accountId, topupQuotaId: topupQuotaId), handler: self.after)
        case "getCreditCards":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let userId = (args["user_id"] ?? args["userId"]) as! String
            let before = args["before"] as? String
            let after = args["after"] as? String
            let perPage = (args["per_page"] ?? args["perPage"]) as? Int
            let organizationCode = (args["organization_code"] ?? args["organizationCode"]) as! String
            client.send(BankAPI.CreditCard.GetCreditCards(userId: userId, before: before, after: after, perPage: perPage, organizationCode: organizationCode), handler: self.after)
        case "createCreditCard":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let token = args["token"] as! String
            let isCardholderNameSpecified = (args["is_cardholder_name_specified"] ?? args["isCardholderNameSpecified"]) as? Bool
            let organizationCode = (args["organization_code"] ?? args["organizationCode"]) as! String
            let userId = (args["user_id"] ?? args["userId"]) as! String
            client.send(BankAPI.CreditCard.CreateCreditCard(token: token, isCardholderNameSpecified: isCardholderNameSpecified, organizationCode: organizationCode, userId: userId), handler: self.after)
        case "deleteCreditCard":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let cardRegisteredAt = (args["card_registered_at"] ?? args["cardRegisteredAt"]) as? String
            let cardUuid = (args["card_uuid"] ?? args["cardUuid"]) as? String
            let organizationCode = (args["organization_code"] ?? args["organizationCode"]) as! String
            let userId = (args["user_id"] ?? args["userId"]) as! String
            client.send(BankAPI.CreditCard.DeleteCreditCard(cardRegisteredAt: cardRegisteredAt, cardUuid: cardUuid, organizationCode: organizationCode, userId: userId), handler: self.after)
        case "topupWithCreditCardMembership":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let userId = (args["user_id"] ?? args["userId"]) as! String
            let cardRegisteredAt = (args["card_registered_at"] ?? args["cardRegisteredAt"]) as? String
            let cardUuid = (args["card_uuid"] ?? args["cardUuid"]) as? String
            let accountId = (args["account_id"] ?? args["accountId"]) as! String
            let amount = args["amount"] as! Int
            let deleteCardIfAuthFail = (args["delete_card_if_auth_fail"] ?? args["deleteCardIfAuthFail"]) as? Bool
            let organizationCode = (args["organization_code"] ?? args["organizationCode"]) as! String
            let requestId = (args["request_id"] ?? args["requestId"]) as? String
            let topupQuotaId = (args["topup_quota_id"] ?? args["topupQuotaId"]) as? Int
            client.send(BankAPI.CreditCard.TopupWithCreditCardMembership(userId: userId, cardRegisteredAt: cardRegisteredAt, cardUuid: cardUuid, accountId: accountId, amount: amount, deleteCardIfAuthFail: deleteCardIfAuthFail, organizationCode: organizationCode, requestId: requestId, topupQuotaId: topupQuotaId), handler: self.after)
        case "topupWithCreditCardMdkToken":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let userId = (args["user_id"] ?? args["userId"]) as! String
            let token = args["token"] as! String
            let accountId = (args["account_id"] ?? args["accountId"]) as! String
            let amount = args["amount"] as! Int
            let organizationCode = (args["organization_code"] ?? args["organizationCode"]) as! String
            let isCardholderNameSpecified = (args["is_cardholder_name_specified"] ?? args["isCardholderNameSpecified"]) as? Bool
            let requestId = (args["request_id"] ?? args["requestId"]) as? String
            let topupQuotaId = (args["topup_quota_id"] ?? args["topupQuotaId"]) as? Int
            client.send(BankAPI.CreditCard.TopupWithCreditCardMdkToken(userId: userId, token: token, accountId: accountId, amount: amount, organizationCode: organizationCode, isCardholderNameSpecified: isCardholderNameSpecified, requestId: requestId, topupQuotaId: topupQuotaId), handler: self.after)
        case "getCvsAuthorizations":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let accountId = (args["account_id"] ?? args["accountId"]) as! String
            let before = args["before"] as? String
            let after = args["after"] as? String
            let perPage = (args["per_page"] ?? args["perPage"]) as? Int
            client.send(BankAPI.Cvs.GetCvsAuthorizations(accountId: accountId, before: before, after: after, perPage: perPage), handler: self.after)
        case "cvsAuthorizeRequest":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let serviceOptionType = (args["service_option_type"] ?? args["serviceOptionType"]) as! String
            let amount = args["amount"] as! Int
            let name1 = args["name1"] as! String
            let name2 = args["name2"] as! String
            let tel = args["tel"] as! String
            let topupQuotaId = (args["topup_quota_id"] ?? args["topupQuotaId"]) as? Int
            let accountId = (args["account_id"] ?? args["accountId"]) as! String
            client.send(BankAPI.Cvs.CvsAuthorizeRequest(serviceOptionType: serviceOptionType, amount: amount, name1: name1, name2: name2, tel: tel, topupQuotaId: topupQuotaId, accountId: accountId), handler: self.after)
        case "cancelCvsAuthorization":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let accountId = (args["account_id"] ?? args["accountId"]) as! String
            let orderId = (args["order_id"] ?? args["orderId"]) as! String
            client.send(BankAPI.Cvs.CancelCvsAuthorization(accountId: accountId, orderId: orderId), handler: self.after)
        case "getCvsAuthorization":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let accountId = (args["account_id"] ?? args["accountId"]) as! String
            let orderId = (args["order_id"] ?? args["orderId"]) as! String
            client.send(BankAPI.Cvs.GetCvsAuthorization(accountId: accountId, orderId: orderId), handler: self.after)
        case "getAccountIndividualNumberIdentification":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let accountId = (args["account_id"] ?? args["accountId"]) as! String
            client.send(BankAPI.Account.GetAccountIndividualNumberIdentification(accountId: accountId), handler: self.after)
        case "identifyIndividual":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let signature = args["signature"] as! String
            let signingCert = (args["signing_cert"] ?? args["signingCert"]) as! String
            let expectedHash = (args["expected_hash"] ?? args["expectedHash"]) as! String
            let name = args["name"] as? String
            let gender = args["gender"] as? String
            let address = args["address"] as? String
            let dateOfBirth = (args["date_of_birth"] ?? args["dateOfBirth"]) as? String
            let accountId = (args["account_id"] ?? args["accountId"]) as! String
            client.send(BankAPI.Account.IdentifyIndividual(signature: signature, signingCert: signingCert, expectedHash: expectedHash, name: name, gender: gender, address: address, dateOfBirth: dateOfBirth, accountId: accountId), handler: self.after)
        case "getAccountTopupQuotas":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let accountId = (args["account_id"] ?? args["accountId"]) as! String
            let status = args["status"] as? String
            let showExpiredForFixedPeriod = (args["show_expired_for_fixed_period"] ?? args["showExpiredForFixedPeriod"]) as? Bool
            let showStartedQuotas = (args["show_started_quotas"] ?? args["showStartedQuotas"]) as? Bool
            let isWithinApplicablePeriod = (args["is_within_applicable_period"] ?? args["isWithinApplicablePeriod"]) as? Bool
            let isUsableAmountLeft = (args["is_usable_amount_left"] ?? args["isUsableAmountLeft"]) as? Bool
            client.send(BankAPI.Account.GetAccountTopupQuotas(accountId: accountId, status: status, showExpiredForFixedPeriod: showExpiredForFixedPeriod, showStartedQuotas: showStartedQuotas, isWithinApplicablePeriod: isWithinApplicablePeriod, isUsableAmountLeft: isUsableAmountLeft), handler: self.after)
        case "getAccountTopupStats":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let accountId = (args["account_id"] ?? args["accountId"]) as! String
            client.send(BankAPI.Account.GetAccountTopupStats(accountId: accountId), handler: self.after)
        case "createJihanpiTransaction":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let nfcTagId = (args["nfc_tag_id"] ?? args["nfcTagId"]) as! String
            let accountId = (args["account_id"] ?? args["accountId"]) as! String
            let requestId = (args["request_id"] ?? args["requestId"]) as? String
            let strategy = args["strategy"] as? String
            client.send(BankAPI.Jihanpi.CreateJihanpiTransaction(nfcTagId: nfcTagId, accountId: accountId, requestId: requestId, strategy: strategy), handler: self.after)
        case "getJihanpiTransactionByOrderId":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let orderId = (args["order_id"] ?? args["orderId"]) as! String
            client.send(BankAPI.Jihanpi.GetJihanpiTransactionByOrderId(orderId: orderId), handler: self.after)
        case "getJihanpiTransactionByRequestId":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let requestId = (args["request_id"] ?? args["requestId"]) as! String
            client.send(BankAPI.Jihanpi.GetJihanpiTransactionByRequestId(requestId: requestId), handler: self.after)
        case "getDetailedShopInformation":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let shopId = (args["shop_id"] ?? args["shopId"]) as! String
            client.send(BankAPI.Shop.GetDetailedShopInformation(shopId: shopId), handler: self.after)
        case "getListOfShops":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let privateMoneyId = (args["private_money_id"] ?? args["privateMoneyId"]) as! String
            let userTagGroupItemId = (args["user_tag_group_item_id"] ?? args["userTagGroupItemId"]) as? String
            let userTagSubgroupId = (args["user_tag_subgroup_id"] ?? args["userTagSubgroupId"]) as? String
            let before = args["before"] as? String
            let after = args["after"] as? String
            let perPage = (args["per_page"] ?? args["perPage"]) as? Int
            client.send(BankAPI.Shop.GetListOfShops(privateMoneyId: privateMoneyId, userTagGroupItemId: userTagGroupItemId, userTagSubgroupId: userTagSubgroupId, before: before, after: after, perPage: perPage), handler: self.after)
        case "getUserTagGroups":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let privateMoneyId = (args["private_money_id"] ?? args["privateMoneyId"]) as! String
            let before = args["before"] as? String
            let after = args["after"] as? String
            let perPage = (args["per_page"] ?? args["perPage"]) as? Int
            client.send(BankAPI.UserTag.GetUserTagGroups(privateMoneyId: privateMoneyId, before: before, after: after, perPage: perPage), handler: self.after)
        case "getUserTagGroupItems":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let organizationCode = (args["organization_code"] ?? args["organizationCode"]) as! String
            let tagGroupId = (args["tag_group_id"] ?? args["tagGroupId"]) as! String
            let subgroupId = (args["subgroup_id"] ?? args["subgroupId"]) as! String
            let before = args["before"] as? String
            let after = args["after"] as? String
            let perPage = (args["per_page"] ?? args["perPage"]) as? Int
            client.send(BankAPI.UserTag.GetUserTagGroupItems(organizationCode: organizationCode, tagGroupId: tagGroupId, subgroupId: subgroupId, before: before, after: after, perPage: perPage), handler: self.after)
        case "getUserTagSubgroups":
            let env = flutterEnvToSDKEnv(ienv: args["env"] as! Int32)
            let accessToken = args["accessToken"] as! String
            let client = Pokepay.Client(accessToken: accessToken, env: env)
            let organizationCode = (args["organization_code"] ?? args["organizationCode"]) as! String
            let tagGroupId = (args["tag_group_id"] ?? args["tagGroupId"]) as! String
            let before = args["before"] as! String
            let after = args["after"] as! String
            let perPage = (args["per_page"] ?? args["perPage"]) as? Int
            client.send(BankAPI.UserTag.GetUserTagSubgroups(organizationCode: organizationCode, tagGroupId: tagGroupId, before: before, after: after, perPage: perPage), handler: self.after)
        default:
            return false
        }
        return true
    }
}
