name: pokepay_flutter_sdk
description: flutter SDK for pokepay
version: 0.0.0
author: pokepay developer team
homepage: https://pay.pocket-change.jp/

environment:
  sdk: ">=2.8.3 <3.0.0"
  flutter: ">=1.17.3"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  logger: ^0.9.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  test: ^1.14.4