name: pokepay_sdk
description: SDK for pokepay
version: 2.0.6
homepage: https://pay.pocket-change.jp/

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.6.0
  logger: ^1.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  test: ^1.21.1

flutter:
  plugin:
    platforms:
      android:
        package: jp.pokepay.pokepay_sdk
        pluginClass: PokepaySdkPlugin
      ios:
        pluginClass: PokepaySdkPlugin