name: pokepay_flutter_sdk
description: SDK for pokepay
version: 1.0.6
homepage: https://pay.pocket-change.jp/

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  json_annotation: ^4.0.0
  logger: ^0.9.1
  intl: ^0.17.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  test: ^1.21.1

flutter:
  plugin:
    platforms:
      android:
        package: jp.pokepay.pokepay_sdk
        pluginClass: PokepaySdkPlugin
      ios:
        pluginClass: PokepaySdkPlugin